### ISSUE TITLE
Add  Login By Facebook and Gmail 

### ISSUE THREAD

**Issue by ali7ussein** [empowerrec/empower#1]
Dear Gamal ,

Please start working with the user signup page using facebook or gmail account.

![image](https://cloud.githubusercontent.com/assets/11144237/12748429/dc622146-c9b2-11e5-9e7a-82cf9712578f.png)

![image](https://cloud.githubusercontent.com/assets/11144237/12748434/ea1f121c-c9b2-11e5-988c-b21588672812.png)

**Comment by ali7ussein** [comment]
Dear Mohamed ,

We need to add the signup information to main page, Also we need to validate for duplicate user names.

Best Regards

**Comment by pmandcs** [comment]
Dear Ali ,

Done.
